[build]
  base = "."
  publish = "build"
  command = "npm run build"

[build.environment]
  NPM_FLAGS = "--legacy-peer-deps"
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production]
  command = "npm ci --legacy-peer-deps && npm run build"

[context.deploy-preview]
  command = "npm ci --legacy-peer-deps && npm run build"

[context.branch-deploy]
  command = "npm ci --legacy-peer-deps && npm run build"